# Generated by Django 5.1 on 2024-08-14 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField(default=24)),
                ('technology', models.TextField()),
                ('telegram', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cv', models.FileField(blank=True, null=True, upload_to='file/')),
                ('resume_eng', models.FileField(blank=True, null=True, upload_to='file/')),
                ('resume_ru', models.FileField(blank=True, null=True, upload_to='file/')),
            ],
        ),
    ]
