# Generated by Django 5.1 on 2024-09-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlistmodel',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
