# Generated by Django 5.1 on 2024-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=100081965327895'),
        ),
    ]
