# Generated by Django 5.1 on 2025-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='message',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
