# Generated by Django 5.1 on 2024-09-09 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_contactlistmodel_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='kurs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
