# Generated by Django 5.1 on 2024-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_contactmodel_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='telegram',
            field=models.URLField(default='https://t.me/diyorbek_backend'),
        ),
    ]
