# Generated by Django 5.1 on 2025-06-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_users_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
