# Generated by Django 5.1 on 2024-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_alter_contactmodel_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='telegram',
            field=models.URLField(),
        ),
    ]
