# Generated by Django 5.1 on 2024-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_alter_contactmodel_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/abdurakhimov_7981/'),
        ),
    ]
