# Generated by Django 5.1 on 2024-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_contactmodel_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurslarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=120)),
                ('dec_found', models.TextField()),
                ('dec_tel_bot', models.TextField()),
                ('dec_posql', models.TextField()),
                ('dec_py_back', models.TextField()),
            ],
        ),
    ]
