# Generated by Django 5.1 on 2024-08-14 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_kurslarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurslarmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='kurs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
