# Generated by Django 5.1 on 2024-08-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_kurslarmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurslarmodel',
            name='dec_posql',
        ),
    ]
